spring:
    application:
        name: bishop-prototype

    audit:
        mode: LOG
        kafka-topic: audit-topic

    kafka:
        bootstrap-servers: localhost:29092
        topicName: "audit-topic"

management:
    endpoints:
        web:
            exposure:
                include: health, info, prometheus
    endpoint:
        prometheus:
            enabled: true
